upload:
  filepath: D:\\image
  baseurl: http://192.168.0.9:8080/image/
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-boot-security?characterEncoding=UTF-8
    username:  root
    password:  root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 2
    maxAction: 20
    maxWaitMillis: 8000
  cache:
    type: redis
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
